- src/components/employees/addemp/persdetails/page.jsx
Updated code for "only" personalInformation page where post api request is sent and data is stored in redux Toolkit successfully.
> personalInformation page updates

- src/api/axios.js
- src/app/hrms/employees/page.js
- src/app/hrms/layout.js
- src/app/hrms/tracker/page.js
- src/app/login/forgot/page.js
- src/app/login/new-password/page.js
- src/app/login/otp/page.js
- src/app/login/page.js
- src/app/login/reset/page.js
- src/components/employees/addemp/documents/Documents.js
- src/components/employees/addemp/equipment/page.jsx
- src/components/employees/addemp/persdetails/page.jsx
- src/components/employees/addemp/profdetails/page.jsx
- src/components/employeesOverview/PersonalInfo.jsx
- src/components/employeesOverview/ProfessionalInfo.jsx
- src/components/login/page.js
- src/components/onboard/CompanyDetails.jsx
- src/components/onboard/Onboarding.jsx
- src/components/onboard/PersonalDetailPreview.jsx
- src/components/onboard/ProfessionalDetailPreview.jsx
- src/components/signup/ConfirmMail.js
- src/components/signup/page.js
- src/redux/slices/Onboardingpersdetails.js
- src/redux/slices/resetPasswordSlice.js
- src/redux/store/store.js
- src/utils/getAccessToken.js
> updated routes for protection

- src/app/hrms/employees/page.js
- src/app/hrms/page.js
- src/app/hrms/tracker/Modal.js
- src/app/hrms/tracker/page.js
integrated API on dashboard, worked on tracker and employee page UI.
> integrated API on dashboard, worked on tracker and employee page UI.

- src/components/location/Countrys.js
- src/components/location/States.js
- src/components/location/city.js
- src/components/login/page.js
- src/components/onboard/CompanyDetails.jsx
- src/components/onboard/Onboarding.jsx
- src/components/onboard/PersonalDetailPreview.jsx
- src/components/onboard/ProfessionalDetailPreview.jsx
- src/redux/slices/Onboardingpersdetails.js
made the number to be 10 digites and zipcode
> made the number to be 10 digites and zipcode

- package-lock.json
- src/app/hrms/layout.js
- src/app/hrms/tracker/Modal.js
> Worked on modal

- next.config.js
- src/components/login/page.js
- src/components/signup/Signup.jsx
> login and signup issues fixed

- next.config.js
- src/app/hrms/tracker/Modal.js
- src/app/hrms/tracker/Modal1.js
- src/app/hrms/tracker/Modal2.js
- src/app/hrms/tracker/Modal3.js
- src/app/hrms/tracker/page.js
worked on  manage invite for specific employee prepared modal per requirement also modified the UI
> worked on  manage invite for specific employee prepared modal per requirement also modified the UI

- next.config.js
- src/app/login/new-password/page.js
- src/app/login/otp/page.js
- src/components/signup/Signup.jsx
issues resolved in signup,reset,otp screens
> issues resolved in signup,reset,otp screens

- package-lock.json
- package.json
- src/app/hrms/employees/employeesOverView/page.js
- src/components/onboard/PersonalDetailPreview.jsx
- src/components/onboard/ProfessionalDetailPreview.jsx
- src/redux/slices/Onboardingpersdetails.js
resolved the errors of webpack
> resolved the errors of webpack

- next.config.js
- src/app/hrms/tracker/Modal3.js
- src/app/hrms/tracker/page.js
fetched the data with the id and rendered it on the profile page
> fetched the data with the id and rendered it on the profile page

- next.config.js
- package-lock.json
- src/app/hrms/employees/employeesOverView/page.js
- src/app/hrms/employees/page.js
- src/app/hrms/page.js
- src/app/login/forgot/page.js
- src/app/login/new-password/page.js
- src/app/onboarding/page.js
- src/components/dashboard/preference/Preference.jsx
- src/components/login/page.js
- src/components/onboard/PersonalDetailPreview.jsx
- src/components/onboard/ProfessionalDetailPreview.jsx
- src/components/signup/Signup.jsx
- src/redux/slices/Onboardingpersdetails.js
added loading indicator and made ui changes
> added loading indicator and made ui changes

- next.config.js
- package-lock.json
- src/components/onboard/CompanyDetails.jsx
- src/components/onboard/PersonalDetailPreview.jsx
- src/components/onboard/ProfessionalDetailPreview.jsx
- src/components/signup/Signup.jsx
- src/redux/slices/Onboardingpersdetails.js
> onboarding issues resolved

- next.config.js
> solving img issue

- src/components/employees/addemp/equipment/page.jsx
- src/components/employees/addemp/persdetails/page.jsx
updated input fields code of forms
> updated input fields code of forms

- package-lock.json
- src/api/axios.js
- src/app/hrms/employees/page.js
- src/app/hrms/page.js
- src/components/dashboard/preference/Preference.jsx
- src/components/dashboard/preference/personaldetails/EditButton.jsx
- src/components/dashboard/preference/personaldetails/Editpersonaldetail.jsx
- src/components/dashboard/preference/personaldetails/Personaldetail.jsx
- src/components/onboard/CompanyDetails.jsx
- src/components/onboard/Onboarding.jsx
- src/components/onboard/PersonalDetailPreview.jsx
- src/components/onboard/ProfessionalDetailPreview.jsx
- src/components/signup/Signup.jsx
made changes in onboarding and preferences
> made changes in onboarding and preferences

- src/components/employees/addemp/persdetails/page.jsx
- src/redux/slices/Details.js
> updated form  validation 

- src/components/dashboard/preference/organization/customfields/Customfeild.jsx
- src/components/employees/addemp/profdetails/page.jsx
change some logic in the department and designation
> change some logic in the department and designation

- package-lock.json
- src/app/login/otp/page.js
- src/components/login/page.js
- src/components/signup/Signup.jsx
> solved some testing issues

- next.config.js
- src/app/hrms/tracker/page.js
- src/components/onboard/CompanyDetails.jsx
- src/components/onboard/Onboarding.jsx
- src/components/onboard/PersonalDetailPreview.jsx
- src/components/onboard/ProfessionalDetailPreview.jsx
replaced notifications with message ,resolved build errors
> replaced notifications with message ,resolved build errors

- src/app/hrms/employees/page.js
Update UI and worked on the tracker page
> Update UI and worked on the tracker page
